server:
  port: 8004
spring:
  application:
    name: xueyuan-ucservice
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.237.150:3306/guli_edu?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/kevin/online/ucenter/mapper/xml/*.xml


#配置阿里云存储信息
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      accessKeyId: LTAI4FpqKUow56nsZHamLDth
      accessKeySecret: uvieDQqJw7aYPHwI43F4TdT9FPY4AI
      bucketName: edu-teacher202051
      #存储头像文件夹名称
      host: career

#eureka注册服务配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8003/eureka/
  #eureka服务器上获取的是服务器的ip地址，否则是主机名
  instance:
    prefer-ip-address: true



#微信开放平台 APPID 及 appsecret 重定向URL
wx:
  open:
    app_id: wxc606fb748aedee7c
    app_secret: 6c94e426cc7f49e29b42231ee202b1a3
    redirect_url: http://yaohuan.work/api/ucenter/wx/callback